steps:
  - label: "build"
    key: "build"
    command: ".buildkite/dad.sh"
    soft_fail: true
    env:
      DURATION: 30
      DURATION_VARIABILITY: 5
      FAILURE_CHANCE: 1
  - group: "tests"
    key: "tests"
    depends_on: "build"
    steps:
      - label: "test %N of %t"
        key: "test"
        command: ".buildkite/dad.sh"
        parallelism: 5
        soft_fail: false
        env:
          DURATION: 20
          DURATION_VARIABILITY: 5
          FAILURE_CHANCE: 5
      - label: "hi"
        key: "hi"
        command: "echo hi"
  - label: "deploy"
    key: "deploy"
    command: ".buildkite/dad.sh"
    soft_fail: true
    env:
      DURATION: 60
      DURATION_VARIABILITY: 30
      FAILURE_CHANCE: 10
    depends_on: "test"
  - label: "finish"
    key: "last"
    command: "echo done"
    depends_on: "deploy"
